version: 0.2

phases:
  install:
    commands:
      - npm install -g bun
      - echo "Installing Node.js dependencies..."
      - bun install
  build:
    commands:
      - echo "Building the Nuxt.js app..."
      - bun run build
  post_build:
    commands:
      - echo "Post build steps..."

artifacts:
  files:
    - "**/*"
  base-directory: .output/server
